services:
  eddy-app:
    build: .
    ports:
      - "8001:8001"
    environment:
      - ASPNETCORE_HTTPS_PORTS=8001
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - EDDY_POSTGRES_HOST=eddy-postgres-db-1
      - TZ=America/Chicago
    volumes:
      - ${APPDATA}/microsoft/UserSecrets/:/home/app/.microsoft/usersecrets
      - ${USERPROFILE}/.aspnet/https/:/https/
    networks:
      - eddy-postgres_default

networks:
  eddy-postgres_default:
    external: true
