[book]
authors = ["Griffin Crane"]
language = "en"
src = "src"
title = "Eddy, the personal management assistant."

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
